spring:
  application:
    name: cardian
  # jpa setting
  jpa:
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQLDialect
      dialect: org.hibernate.dialect.MariaDB103Dialect
#      show_sql: true
      format_sql: true
#      use_sql_comments: true

    show-sql: true
    defer-datasource-initialization: true
    open-in-view: true

  # datasource setting
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    driver-class-name: org.hibernate.dialect.MySQL8InnoDBDialect
#    url: jdbc:mysql://127.0.0.1:3306/cardian?serverTimezone=UTC
    url: jdbc:mariadb://i10a803.p.ssafy.io:3306/cardian?serverTimezone=UTC
    username: root
    password: a803

